apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ugate
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    client.knative.dev/user-image: gcr.io/dmeshgate/ugate
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    #run.googleapis.com/sessionAffinity: 'true'
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: gcr.io/dmeshgate/ugate
        autoscaling.knative.dev/maxScale: '1'
        #run.googleapis.com/sessionAffinity: 'true'
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      containers:
        - image: gcr.io/dmeshgate/ugate:latest
          # Ugate is built with ko, which overrides command to be
          # /ko-app/ugate.
          command: /usr/local/bin/run.sh
          env:
            - name: test
              value: value
            # Dev version connects to this reverse proxy
            - name: DOMAIN
              value: c1.webinf.info
            # Dev version accepts SSH connections with this key
            - name: SSH_AUTH
              value: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBI/j2SLhiCu+2jueEOMpO1rsjmbZKxWPuivaGMQYyezlcHZvFIrp0liZkjwETsI2KTIuXYhr32lbQClH2vR55QU= costin@costin16"
          ports:
            - name: h2c
              containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: 256Mi
  traffic:
    - percent: 100
      latestRevision: true
